name: Build Docker Image, Deploy to ECR, Start Containers & Read Env vars from Secrets Manager
on:
  push:
    branches:
      - master
      - staging
      - development
      - QAv*
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v1
      - name: Extract branch name
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - uses: gitgregoryjones/secretsdeploy@v37
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
          region: us-east-1,us-east-2
          project_name: inthearena-react
          stage: ${{ steps.extract_branch.outputs.branch }}
          slack_hook_url: ${{ secrets.SLACK_HOOK_URL }}
